 /******************************************************************************
 *
 * Module: ultrasonic
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ultrasonic driver
 *
 * Author: Mohamed Hisham
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_


#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define TRIGGER_PORT	PORTB_ID
#define TRIGGER_PIN 	PIN5_ID
#define ECHO_PORT		PORTD_ID
#define ECHO_PIN		PIN6_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 *  Description:
  * Initialize the ICU driver as required.
  * Setup the ICU call back function.
  * Setup the direction for the trigger pin as output pin through the GPIO driver.
 * Inputs: None
 * Return: None
*/
void ULTRASONIC_init(void);

/*
 * Description:
  * Send the Trigger pulse to the ultrasonic.
 * Inputs: None
 * Return: None
*/
void ULTRASONIC_Trigger(void);

/*
 * Description
  * Send the trigger pulse by using Ultrasonic_Trigger function.
  * Start the measurements by the ICU from this moment.
 * Inputs: None
 * Return: The measured distance in Centimeter.
*/
uint16 ULTRASONIC_readDistance(void);

/*
 * Description
  * This is the call back function called by the ICU driver.
  * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 * Inputs: None
 * Return: None
 */
void ULTRASONIC_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
